### Numpy: Packages for Multidimensional array
#### Vector (1d)
#### Matrix (2d or 1d)

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3,4]
np.array(simple_list)

array([1, 2, 3, 4])

In [3]:
list_of_list=[1,2,3],[4,5,6],[6,7,8]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(4,dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
np.linspace(0,1,5)    ## equally space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.eye(3)    ## identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(2,2)    ## random no. to form a matrix

array([[0.30741077, 0.34536448],
       [0.43657462, 0.19270485]])

In [15]:
np.random.randn(2,4)

array([[ 0.37307427, -0.08427136,  0.37777562,  1.00065981],
       [-0.45725397, -2.64815961, -0.27612549,  0.19604763]])

In [16]:
np.random.randint(1,4,10)

array([2, 2, 1, 2, 2, 1, 3, 2, 1, 3])

In [17]:
sample_array=np.arange(2,16)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
rand_array=np.random.randint(2,20,5)
rand_array

array([ 9, 15, 15, 17, 10])

In [20]:
sample_array.min()

2

In [21]:
sample_array.argmin()

0

In [22]:
rand_array.argmin()

0

In [24]:
rand_array.min()

9

In [25]:
rand_array.argmax()

3

In [26]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a=np.random.rand(2,3)
a

array([[0.68347233, 0.40069996, 0.79428793],
       [0.67709447, 0.07884076, 0.68008863]])

In [29]:
sample_array=sample_array.reshape(7,2)
sample_array

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [30]:
sample_array[2]=15
sample_array

array([[ 2,  3],
       [ 4,  5],
       [15, 15],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [31]:
sample_array[2:5]

array([[15, 15],
       [ 8,  9],
       [10, 11]])

In [32]:
sample_array[2:5]=100
sample_array

array([[  2,   3],
       [  4,   5],
       [100, 100],
       [100, 100],
       [100, 100],
       [ 12,  13],
       [ 14,  15]])

### Two-Dimensional Array

In [33]:
import numpy as np

In [34]:
sample_matrix=np.array([[24,13,2,15],[15,2,54,65],[23,56,74,23]])
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [23, 56, 74, 23]])

In [35]:
sample_matrix[2][2]

74

In [36]:
sample_matrix[1][3]

65

In [37]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [74, 23]])

In [38]:
sample_matrix[:,2]

array([ 2, 54, 74])

In [39]:
sample_matrix[2,3]

23

In [40]:
sample_matrix[0:,2:]

array([[ 2, 15],
       [54, 65],
       [74, 23]])

In [41]:
sample_matrix[2]

array([23, 56, 74, 23])

In [42]:
sample_array=np.arange(0,31)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [44]:
np.exp(sample_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13])

In [45]:
np.sqrt(sample_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558])

In [46]:
np.max(sample_array)

30

In [47]:
np.min(sample_array)

0

In [48]:
np.log(sample_array)

C:\Users\YASHPA~1\AppData\Local\Temp/ipykernel_8004/988743405.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738])

In [49]:
np.square(sample_array)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841, 900], dtype=int32)

In [50]:
np.argmin(sample_array)

0

In [51]:
np.std(sample_array)

8.94427190999916

In [52]:
np.var(sample_array)

80.0

In [53]:
np.mean(sample_array)

15.0

In [58]:
array=np.random.randn(3,4)
array

array([[-1.75940279,  1.30890162, -0.31749549,  1.23597311],
       [ 0.76149241,  0.23450701, -0.214925  ,  2.22221388],
       [ 0.68827933,  0.62276984, -1.44018577, -1.22863133]])

In [59]:
np.round(array,decimals=2)

array([[-1.76,  1.31, -0.32,  1.24],
       [ 0.76,  0.23, -0.21,  2.22],
       [ 0.69,  0.62, -1.44, -1.23]])

In [60]:
fruits=np.array(['apple','orange','mango','orange','apple'])
np.unique(fruits)

array(['apple', 'mango', 'orange'], dtype='<U6')